# fly.io 배포를 위한 Dockerfile

# 사용할 Node.js 버전을 지정하는 베이스 이미지 선택
FROM node:22-alpine

# 애플리케이션 파일들이 위치할 디렉토리 생성
WORKDIR /app

# 전체 파일 복사
COPY . .

# 의존성 설치
RUN npm install


# Next.js 애플리케이션 빌드
RUN npm run build

# 앱이 실행될 포트 지정
EXPOSE 3000

# 애플리케이션 실행 명령어
CMD ["npm", "start"]
