name: Frontend Deploy
on:
  push:
    branches:
      - main 
      # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: 
      group: deploy
      cancel-in-progress: true # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_NAVER_SERVICE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_NAVER_SERVICE_CLIENT_ID }}" > ./frontend/.env

      - name: Deploy to Fly.io
        run:
          flyctl deploy --remote-only ./frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
